### ISSUE TITLE
Extension actions as classes

### ISSUE THREAD

**Issue by bejoinka** [awell-health/awell-extensions#122]
Let's do some discovery on supporting actions as classes to support a more familiar API pattern around dependency injection (i.e. decorators).

**Comment by radoslawstepinski** [comment]
Rewriting actions as classes would open up a way to inject services more easily and cleanly, as with the current solution the types are getting very complex.

We could keep the plain object API as an alternative, this shouldn't be too difficult. We could check if the action is a plain object and then treat it like we currently do.

We could use typedi or some other DI system, but from what I can see:

typedi hasn't been updated in 2 years, and with decorators becoming stage 3, I wouldn't go this way
There's typed-inject, but it doesn't use decorators and wouldn't be much cleaner than what I already proposed.
There's InversifyJS, but it also doesn't seem active, much like typedi.
Same deal with TSyringe, looks like it's unmaintained
This pretty much leaves us with having to implement DI ourselves. A simple system with just enough features to meet our needs wouldn't be too complex, in fact, I've already done something like this. Some simple decorators would take it to the next level.

This brings me to the next point - should we use the current experimental decorators API, or switch to the stage 3 proposal API? There's an argument for both, starting with stage 3 means we're going to have an easier time transitioning to the finished thing, but it somewhat limits us in what we can do right now. For example, the current stage 3 proposal doesn't include parameter decorators, though they might (and probably will) be included sometime in the future. We don't need parameter decorators to facilitate constructor injection, we can just use a class decorator factory with an array parameter specifying requested services in the order they appear in the constructor, like this:

@Action(['serviceA', 'serviceB'])
class ExampleAction {
  constructor(a: A, b: B) {}
}
We could also stick with experimental decorators, which according to TS devs, will continue to be supported for the foreseeable future (presumably at least until parameter decorators make it to ES).

Would love to hear your thoughts and suggestions on this.

**Comment by ebomcke-awell** [comment]
There are two criteria to apply to pick the right solution:

1. Which solution has the lowest total cost of ownership (so development AND maintenance cost) ?
2. Which solution delivers the best developer experience for Jasmine ?

IMO refactoring the actions into classes and adding backwards compatible support for objects has a much higher TCO than plugging an existing DI library into the current design. We're creating new code that is marginally related to core extension functionality (the DI system is a tool to inject actual core functionality in actions), and we're adding new points of failure to the extension system (what if DI system fails ? what if backwards compatible mechanism fails ? ...).

It's good that you looked at the activity in the main DI libraries and the fact that none of them look like they are actively maintained is a concern for long term maintainability, however it's also worth pointing out that we've used `typedi` in production for two years now without running into any issue.

So given our current context (small team, currently focusing on reducing friction), I would rather choose the safe option (`typedi`) and find ways to mitigate the lack of decorators for better dev ex (pass custom typed container that make it easy to get the right service inside an activity handler for example) then invest in a custom and unproven solution, especially given the uncertainty around the right choice for decorators.

Admittedly it is nowhere near as cool as creating a custom DI system with custom decorators, but IMO it's the right choice for us right now.

**Comment by radoslawstepinski** [comment]
### Jasmine
I think that decorators would be the best DX here. Jasmine could have a parent class that for example handles creating an API client. The actions would extend this class and already have this repeatable logic included. 
Right now there's really no way of achieving the same with plain objects. This results in a lot of copy-paste code in multiple actions, which spells a bad time for Jasmine. 

Also injecting anything into `onActivityCreated` requires rewriting the interface for Action, adding an additional parameter for the container. While this doesn’t require rewriting all actions, it DOES require rewriting all tests, which now need to provide that additional argument, even if the target action won’t ever use it. This can be mitigated by declaring the actions with the `satisfies` operator. Tests receive the narrower type, allowing us to skip the additional argument, while the server still only knows the broader Action type.  The above solution is still bad DX for Jasmine, as reusability is limited. She still has to do repeatable stuff with the services she receives in every action. Yes, she could, for example, have a factory for the API client, but this still requires something like `const api = makeAPIClient(payload.settings, services.someService)` in every action. If Jasmine changes how the factory function works, maybe it requires an additional service or some payload data, she now needs to fix this multiple times.

The solution I proposed while working with token cache is probably the best we can do for Jasmine in this regard, but comes at the price of very complex types, so higher maintenance cost for us.

Another possibility classes open up for Jasmine, is removing even more duplicated code like error handling. She could define a base parent abstract class for her actions, which would have the activity handler, and an abstract inner handler, implemented by child classes. Now that I think about it, this approach would remove the need for decorators, as we could pass the DI container to the handler, while still having a lot of reusability.

Consider the following example:
```typescript
interface Action {
    handler: (data: any) => void
}

abstract class BaseAction implements Action {
    handler = (data: any) => {
        // Do some common stuff here
        this.innerHandler(data);
        // Maybe even more common stuff
    }

    abstract innerHandler: (data: any) => void
}

class ConcreteAction extends BaseAction {
    innerHandler = (data: any) => {
        // Do actual action handling
    }
}
```

### Our experience
I wouldn’t scratch classes just because it adds some complexity to the extension server (checking whether the action is a plain object or a class). All other options add complexity here or elsewhere. For example, the currently proposed solution is even more complex for the extension server, and the lightweight solution of just adding a parameter to the activity handler means bad DX and more complexity for Jasmine in the extension code. We’re also Jasmine sometimes, so this is a future cost for us too.  In fact, checking whether the action is a class or a plain object is as simple as just using `typeof action`, which returns “object” for plain object, and “function” for a class (note: not a class instance). The interfaces of the plain object and the class would be compatible, the only difference is that now we get to have a constructor we can inject stuff into, a reusability layer for Jasmine, and we can slap some decorators on it (even later on if we don’t decide we want to include them right now). Once the extension server instantiates the action, the class instance and the plain object are treated exactly the same. TBH I don’t see much room for bugs here.

_To decorate or not to decorate:_ if we use `typedi` and have actions as classes, we can just `@Inject(‘serviceName’)` in the constructor. However, I would still be inclined to use a custom decorator for actions, so as to not expose our DI system to Jasmine.   All things considered, I’m worried about `typedi`, since from what I can see its documentation seems to be very fragmentary (e.g. `@Service decorator` and `Container API` pages are blank), which could give me a lot of trouble with implementation as I’ve never worked with this library before.  

### What I would propose: 
- Adding actions as classes, keeping the plain object API - the better DX for Jasmine (and possibly for us in the future) is just so valuable that I don’t see the added complexity for backwards compatibility ever outweighing this. 
- Using `typedi` (or some other DI lib) instead of implementing our own solution.
- Exposing the container in the activity handler call or using a custom decorator to inject requested services into the constructor - again, I’d be in favor of a custom decorator, as in this case Jasmine doesn’t have to worry about the container API and we don’t have to expose the container.

TBH I feel like we're going to have to rewrite actions as classes sometime in the future, and I think it's better to do it sooner rather than later when we're going to have tons of extensions and actions in need of refactoring.

And yes, I recognize the "cool factor", but it didn't give it too much weight.

  What do you think?

**Comment by bejoinka** [comment]
Good discussion. Given extensions are still in beta, if we decide we want to go the classes route then we shouldn't support both classes and functions. Everything is still just too new.

Why don't we start defining requirements? They should be problem-centric requirements (rather than solution-specific), such as:
- Remove the unnecessary boilerplate around `onError(if (err typeof ZodError) ...)`
- Provide an easy way to access services that are shared across extensions
- Include guardrails around those services given we are injecting a singleton
- Reduced boilerplate around tests, to encourage high coverage
- etc.

If we decide to move forward w/something, we should wrap it up before June 1 -- we can pick up the timeline conversation in slack

Thanks!

**Comment by radoslawstepinski** [comment]
This would be my perspective on this:
1. Jasmine should have easy access to the services she requires, but we shouldn't expose the whole container
2. We should protect the services against buggy/malicious code with some throttling mechanism, for sensitive data such as auth tokens we should also ensure Jasmine only has access to her own data
3. Jasmine should be able to easily reuse code for things like setting up API clients or error handling

**Comment by bejoinka** [comment]
closing out this issue given it would no longer be implemented first here, but instead inside of [extensions-core](https://github.com/awell-health/extensions-core).
