### ISSUE TITLE
[EXT-6] New extension: TalkDesk

### ISSUE THREAD

**Issue by michal-grzelak** [awell-health/awell-extensions#189]
<sub>From [SyncLinear.com](https://synclinear.com) | [EXT-6](https://linear.app/awell/issue/EXT-6/talkdesk-extension)</sub>

**Comment by nckhell** [comment]
Talkdesk (in the first stage of our integration) will be used to manage phone calls and SMS sending. 

# Authentication

Talkdesk authentication [has to be made using OAuth2](https://docs.talkdesk.com/docs/authentication)

**Two options:**
* ✅ Client credentials grant
* 🛑 User authorization grant

# Actions

## Contact sync

https://docs.talkdesk.com/docs/implementing-a-contact-synchronization

## Trigger a flow

Once the contact is created into Talkdesk we need to be able to execute flows in order to trigger SMS to the patient, this is 
done by [triggering a flow inside talkdesk](https://docs.talkdesk.com/reference/flows-api-ref).

# Webhooks

We also need to listen [to talkdesk webhooks](https://docs.talkdesk.com/docs/webhook-trigger-api)

# Questions

- Is the only way to create contacts via synchronization?
- Is Talkdesk a transactional platform where you can trigger an action only for one patient or does it do things in bulk?
- Can you explain the use case for Talkdesk webhooks?
