### ISSUE TITLE
[EXT-34] [Sendbird] NEW Update a ticket action

### ISSUE THREAD

**Issue by rahulkeerthi** [awell-health/awell-extensions#231]
Based on [https://sendbird.com/docs/desk/platform-api/v1/features/ticket#2-update-a-ticket](https://sendbird.com/docs/desk/platform-api/v1/features/ticket#2-update-a-ticket)

Fields: `ticket_id` (string), `priority` (string, see docs for possible values), `relatedChannelUrls`(string)
Data points: None required

<sub>From [SyncLinear.com](https://synclinear.com) | [EXT-34](https://linear.app/awell/issue/EXT-34/[sendbird]-new-update-a-ticket-action)</sub>

**Comment by rahulkeerthi** [comment]
[https://awellhealth.slack.com/archives/C05CNA7RD9C/p1693461128405689](https://awellhealth.slack.com/archives/C05CNA7RD9C/p1693461128405689)

**Comment by nckhell** [comment]
> Data points: TBC

@rahulkeerthi The principle I try to follow and I'd suggest we hold on to is that requesting the actual resource always happens via a dedicated action. In this case a "Get ticket" action.

**Why?**
- We clearly segregate responsibilities of actions. Some actions do the "C", "U", and "D" in "CRUD", others do the "R"
- It's easier to maintain. Imagine that the "Create patient" and "Update patient" actions also return all patient data points but at some point, there's a change that needs to be done to these data points. Instead of having to update three actions (Create, update, and get patient) we can just update one action (get patient)
- That means in many cases adding two actions to your care flow. First, updating a resource and second, retrieving the updated details from the resource but I think this is acceptable.

WDYT?

**Comment by rahulkeerthi** [comment]
> WDYT?

@nckhell yeah, I'm aligned with that. Our system already acknowledges a successful response (via the activity itself) so no need to map any data points with Update actions unless there's a very specific exception. 

In this case I just wanted to understand the use case with users (and confirm there was no exception needed here) before proceeding. As you'll see, it's updated to `None required` now

**Comment by rahulkeerthi** [comment]
Resolved, updated your rights to admin
