### ISSUE TITLE
[EXT-58] Create a CLI Tool for Code Generation

### ISSUE THREAD

**Issue by kubiak85** [awell-health/awell-extensions#260]
We propose developing a command-line interface (CLI) tool that will facilitate code generation for various aspects of extension development. The full version of this tool will have the capability to generate code for actions, webhooks, extension settings,  fields, datapoints, and basic schemas.

The implementation of this tool is envisioned as a gradual process, beginning with the creation of a foundational directory structure, datapoints, and fields generation commands.

The tool aims to:

- Streamline Extension Development: Simplify the process of creating extensions for our platform by automating repetitive tasks associated with code generation.

- Enhance Productivity: Allow developers to focus more on the core logic of their extensions rather than spending time on boilerplate code.

- Standardize Code Quality: Ensure that generated code adheres to best practices and follows established coding conventions.

- Improve Developer Experience: Provide an intuitive CLI interface for developers to interact with the tool, making extension development more accessible.

- Expand Capabilities: Over time, add more commands and features to cover a wider range of extension development needs.

**The initial phase of development will focus on:**

- Create CLI 
- Creating a directory structure for extensions.
- Generating basic data points.
- Generating basic fields.
- Generate README file 

<sub>[EXT-58](https://linear.app/awell/issue/EXT-58/create-a-cli-tool-for-code-generation)</sub>

**Comment by rahulkeerthi** [comment]
@mateusz.kubiak Kindly provide updates here, even if short, and mention if anything is blocking you (even if you think you can resolve it with more time). 

As this is not scoped work (you are figuring out both what to do and how to do things instead of trying to specifically implement something), there's more burden on you than usual to be transparent on your process and thinking.

As a request, I'll set a deadline for tomorrow for you to prepare a document explaining in more detail what is being produced here, which will accompany work you are doing. If you believe this will not be useful or is too soon to create, let me know and why — I am flexible! I have included some example questions below, you don't have to answer all of them, but I think they are useful to know the answer to:

* Create CLI: how do you intend the CLI to work, what options will it provide, how many commands and what do they do, what is required to configure it
* Creating a directory structure for extensions: what assumptions are we making here? how do we ensure this is 'learned' correctly given we have inconsistent directory structures now (old and new way)
* Generating basic data points: what are basic data points? are these just placeholders to be manually replaced?
* Generating basic fields: what are basic fields? are these also placeholders? what about extension settings? schemas?
* Generate README file: what is the principle here? do we give any instructions on the kind of language to use?

If you can also document the LLM side of things, that would be good. It can just be a few paragraphs to explain what tool(s) you have chosen and what you are doing with those tools to prepare the above things.
